version: "3.8"

volumes:
  database:
    external: false

services:
  app:
    image: eduardokyc/pld:latest
    depends_on:
      - base
    ports:
      - "80:80"
    
  base:
    image: eduardokyc/db_pld:latest
    volumes:
      - "database:/var/lib/mysql"
    ports:
      - "3306:3306"